project_id = "cqlbidkagiknfplzbwse"

[functions.send-invitation-email]
verify_jwt = false

[functions.send-alert-email]
verify_jwt = false

[functions.test-data-seeder]
verify_jwt = false

[functions.process-message-reminders]
verify_jwt = true